current_dataset: one_person
current_model: ResNet # BaselineEEGReconstruction, AlexNet, SqueezeNet, ResNet, TCNAE, ResNetLatentEEG
current_loss_function: MSELoss # MSELoss, ApproxWassersteinDistanceLoss, TimeSeriesSimilarityLoss
used_channels: [O1, Oz, O2, T7, T8, TP7, TP8, P7, P8, PO7, PO8] # add channels, or use 'All' for enabling all channels (see list of channels in utils.constants.py)
task: eeg # class, eeg

transformations:
  eeg:
    scaling: 1000000
    new_freq: 100
    low_pass: 40
    high_pass: 1
  image:
    dimensions: 224

early_stopping:
  patience: 1000
  min_change: 0

datasets:
  general:
    test_size: 0.1
    validation_size: 0.1
  
  one_person:
    tmin: 50
    tmax: 250
    batch_size: 128
    channels: 63

models:
  general:
    learning_rate: 0.001
    optimizer: Adam # Adam, SGD
    weight_decay: 0.001
    dropout: 0.5
    max_epochs: 1000
    freeze: false
    pretrained: true # true, false

  tcnae:
    avgpool_size: 4

  resnet:
    n_blocks: 4 # 0-4
    